---

- name: Add vProtect yum repository
  yum_repository:
    name: vProtect
    description: vProtect repo
    baseurl: "{{ vprotect_repo }}"
    gpgcheck: no
    
- name: Update all yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
